apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketData
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: marketData
  template:
    metadata:
      labels:
        app: marketData
    spec:
      containers:
        - image: construir image
          name: marketData
          ports:
            - containerPort: 5000